/**
 * RL (Reinforcement Learning) Animation
 *
 * Vertical layout that fits reveal.js slides without overflow.
 * Three actors: LLM generador, LLM en entrenamiento, Verificador
 * Steps through the RL loop with a "Siguiente" button.
 *
 * Usage: initRlAnim({ containerId: 'rl-anim-demo' })
 */

function initRlAnim(opts) {
  var container = document.getElementById(opts.containerId);
  if (!container) return;

  var problems = [
    {
      prompt: 'Si 8 obreros construyen un muro en 10 horas, ¿cuántas horas tardan 5 obreros en construir 3 muros?',
      answer: '48',
      attempts: [
        { text: 'Un muro = 8×10 = 80 obrero-h. Tres muros = 240. Con 5: 240÷5 = 48 h.', correct: true },
        { text: 'Menos obreros, más muros... 10×3 = 30, ÷5... no, ×5... 24 h.', correct: false },
        { text: 'Inversa: ×(8/5). Directa: ×3. Entonces 10×1.6×3 = 48 h. Verifico: 5×48 = 240 ✓', correct: true },
        { text: 'Proporcional: 10 × 5/8 × 3 = 18.75 h.', correct: false },
      ]
    }
  ];

  var step = 0;

  function getP() { return problems[0]; }

  function actorBox(label, color, borderColor, content, active) {
    var opacity = active ? '1' : '0.4';
    return '<div style="flex: 1; background: var(--bg-code); border-radius: 6px; padding: 8px 10px; ' +
      'border-left: 3px solid ' + (active ? borderColor : 'var(--text-muted)') + '; min-height: 52px;">' +
      '<div style="color: ' + color + '; font-weight: bold; margin-bottom: 4px; font-size: 1.05em;">' + label + '</div>' +
      '<div style="color: var(--text-muted); font-size: 0.9em; line-height: 1.4; opacity: ' + opacity + ';">' + content + '</div>' +
      '</div>';
  }

  function render() {
    var p = getP();
    var html = '<div style="font-size: 0.6em;">';

    // Row 1: Three actors
    html += '<div style="display: flex; gap: 8px; align-items: stretch;">';

    html += actorBox(
      'LLM generador',
      'var(--accent-secondary)', 'var(--accent-secondary)',
      step >= 1 ? 'Genera problemas con respuesta verificable' : 'Esperando...',
      step >= 1
    );

    html += actorBox(
      'LLM en entrenamiento',
      'var(--text-primary)', 'var(--text-primary)',
      step >= 2 ? 'Genera múltiples intentos de solución (estocástico &mdash; cada uno es distinto)' : 'Esperando problema...',
      step >= 2
    );

    html += actorBox(
      'Verificador',
      'var(--accent)', 'var(--accent)',
      step >= 3 ? 'Compara cada intento con la respuesta correcta' : 'Esperando intentos...',
      step >= 3
    );

    html += '</div>';

    // Row 2: Problem
    if (step >= 1) {
      html += '<div style="background: var(--bg-secondary); border-radius: 6px; padding: 8px 12px; margin-top: 8px; border: 1px solid var(--accent-secondary);">';
      html += '<div style="display: flex; justify-content: space-between; align-items: baseline;">';
      html += '<div style="color: var(--text-primary); line-height: 1.4; flex: 1;">' + p.prompt + '</div>';
      html += '<div style="color: var(--text-muted); font-size: 0.85em; flex-shrink: 0; margin-left: 12px;">Rta: <span style="color: var(--accent);">' + p.answer + '</span> <span style="color: var(--text-muted);">(oculta al modelo)</span></div>';
      html += '</div></div>';
    }

    // Row 3: Attempts (generated by "LLM en entrenamiento")
    if (step >= 2) {
      html += '<div style="display: flex; gap: 6px; margin-top: 6px;">';
      for (var i = 0; i < p.attempts.length; i++) {
        var a = p.attempts[i];
        var showScore = step >= 3;
        var border = showScore
          ? (a.correct ? '#27ae60' : '#e74c3c')
          : 'var(--text-muted)';
        var opacity = (showScore && !a.correct) ? '0.4' : '1';

        html += '<div style="flex: 1; background: var(--bg-secondary); border-radius: 6px; padding: 6px 8px; ' +
          'border: 1px solid ' + border + '; opacity: ' + opacity + '; transition: opacity 0.3s, border-color 0.3s;">';
        html += '<div style="color: var(--text-muted); font-size: 0.8em; margin-bottom: 3px;">Intento ' + (i + 1) + '</div>';
        html += '<div style="color: var(--text-primary); line-height: 1.4; font-family: var(--font-mono); font-size: 0.9em;">' + a.text + '</div>';
        if (showScore) {
          html += '<div style="margin-top: 3px; font-weight: bold; font-size: 0.9em; color: ' +
            (a.correct ? '#27ae60' : '#e74c3c') + ';">' +
            (a.correct ? '= ' + p.answer + ' ✓' : '≠ ' + p.answer + ' ✗') + '</div>';
        }
        html += '</div>';
      }
      html += '</div>';
    }

    // Row 4: Reinforcement
    if (step >= 4) {
      html += '<div style="background: var(--bg-code); border-radius: 6px; padding: 6px 12px; margin-top: 6px; display: flex; align-items: baseline; gap: 8px;">';
      html += '<span style="color: var(--accent); font-weight: bold; flex-shrink: 0;">Actualizar:</span>';
      html += '<span style="color: var(--text-muted);">subir la probabilidad de los tokens que llevaron a respuestas correctas en el <strong style="color: var(--text-primary);">LLM en entrenamiento</strong>.</span>';
      html += '</div>';
    }

    html += '</div>'; // end wrapper

    // Controls
    html += '<div style="display: flex; justify-content: space-between; align-items: center; margin-top: 8px; font-size: 0.6em;">';

    var labels = [
      'Inicio',
      'Un LLM genera un problema con respuesta verificable',
      'El LLM en entrenamiento genera múltiples intentos',
      'El verificador evalúa cada intento',
      'Se refuerzan las soluciones correctas en el modelo',
      'Nuevo problema &mdash; repetir ×miles'
    ];
    html += '<div style="color: var(--text-muted); font-style: italic;">' + labels[Math.min(step, labels.length - 1)] + '</div>';

    html += '<div style="display: flex; gap: 6px;">';
    if (step > 0) {
      html += '<button onclick="window._rlAnimPrev()" style="background: var(--bg-secondary); color: var(--text-muted); border: 1px solid var(--text-muted); border-radius: 4px; padding: 3px 12px; cursor: pointer; font-family: var(--font-body); font-size: 1em;">&larr;</button>';
    }
    if (step < 4) {
      html += '<button onclick="window._rlAnimNext()" style="background: var(--accent); color: var(--bg-primary); border: none; border-radius: 4px; padding: 3px 12px; cursor: pointer; font-family: var(--font-body); font-size: 1em; font-weight: bold;">Siguiente &rarr;</button>';
    }
    html += '</div></div>';

    container.innerHTML = html;
    // Tell reveal.js to recalculate slide scaling after content changes
    if (window.Reveal && Reveal.layout) Reveal.layout();
  }

  window._rlAnimNext = function() {
    if (step < 4) {
      step++;
      render();
    }
  };

  window._rlAnimPrev = function() {
    step--;
    if (step < 0) step = 0;
    render();
  };

  render();
}
